// <auto-generated />
namespace JobMe.Web.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddProperty_ApplyedOn_InJobOffer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProperty_ApplyedOn_InJobOffer));
        
        string IMigrationMetadata.Id
        {
            get { return "201403230920010_AddProperty_ApplyedOn_InJobOffer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
